# Generated by Django 5.1.1 on 2024-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_quantity_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
